spring:
  application:
    name: Stroy1Click - NotificationService
  data:
    redis:
      host: redis
      port: 6379
  cache:
    type: redis
    cache-names: redis-cache
  config:
    activate:
      on-profile: prod
server:
  port: 2020

redisson:
  host: redis
  port: 6379
  username: default
  password: password

otel:
  service:
    name: "notification-service"
  traces:
    exporter: "otlp"
    sampler: "always_on"
  metrics:
    exporter: "otlp"
    export:
      interval: 5000
  logs:
    exporter: "otlp"
  exporter:
    otlp:
      protocol: "grpc"
      endpoint: "http://localhost:4317"